
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Mayank Sharma
tagline: Bachelor of Engineering from Technocrats Institute of Technology,Bhopal
pic: profile.jpg  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: mayank202020@rediff.com
phone: 07049226584
website: sharmayank.blogspot.in/ #do not add http://
linkedin: mayank-sharma-778755117/
github: killermayank
twitter: '@mayanksharma'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
